services:
  redis:
    image: redis:alpine


  nginx:
    image: brayandevzn/n8n_server:proxy

    depends_on:
      - api_n8n


  api_n8n:
    image: brayandevzn/n8n_server:api

    env_file:
      - src/config/.env

    depends_on:
      - redis
      - n8n
  
  n8n:
    image: brayandevzn/n8n_server:n8n

    

  




    
   