events {}

http {
    server {
        listen 800;

        # QUALQUER request pública
        location / {
            # Primeiro verifica na sua FastAPI
            auth_request /verify;

            # Depois manda o MESMO path para o n8n
            proxy_pass http://n8n:5678;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # Só o próprio Nginx consegue chamar
        location = /verify {
            internal;

            proxy_pass http://api_n8n:8000/auth/;

            proxy_pass_request_body off;
            proxy_set_header Content-Length "";

            proxy_set_header Cookie $http_cookie;
            proxy_set_header Authorization $http_authorization;
        }
    }
}