name: docker build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main


jobs:

    build:

        runs-on: ubuntu-latest

        environment: prod

        env:
                rate_limit: ${{ secrets.RATE_LIMIT }}
                global_rate_limit: ${{ secrets.GLOBAL_RATE_LIMIT }}
                origin: ${{ secrets.ORIGIN }}
                environment: ${{ secrets.ENVIRONMENT }}
                block: ${{ secrets.BLOCK }}
                block_limit: ${{ secrets.BLOCK_LIMIT }}

        steps:

            - uses: actions/checkout@v4

            - name: Create .env
              run: |
                    cat > .env << EOF
                    REDIS_HOST=${{ secrets.REDIS_HOST }}
                    REDIS_PORT=${{ secrets.REDIS_PORT }}
                    JWT_SECRET=${{ secrets.JWT_SECRET }}
                    DATABASE_URL=${{ secrets.DATABASE_URL }}
                    EOF

            - name: init docker
              run: docker compose -f compose.n8n.yml up -d --build

            - name: test api
              run: curl http://localhost:800

            